# Generated by Django 4.2.7 on 2023-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_owner_alter_mailingmessage_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Статус активности'),
        ),
    ]
