# Generated by Django 4.2.7 on 2023-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailingsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('STATUS_OK', 'Успешно'), ('STATUS_FAILED', 'Ошибка')], default='STATUS_OK', max_length=20, verbose_name='Статус'),
        ),
    ]
